### ISSUE TITLE
Investigate the applicability of CronJob spec to schedule Tasks in Kubernetes

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-scheduler-kubernetes#1]
As a developer, I'd like to implement the [Scheduler SPI](https://github.com/spring-cloud/spring-cloud-scheduler) for kubernetes using the [`CronJob`](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/) spec.

**Acceptance:**
- The `CronJob` spec is at BETA; study the integration possibilities, limitations, and document it. 
- Review the cron-expression requirements for Kubernetes and the current validation semantics provided through `CronJob`,  if any.
- Look into the Fabric8 java-client implementation, and study it from API completeness and the SPI contract perspective.

**Comment by chrisjs** [comment]
see gdoc "Fabric8 Scheduler SPI Spike"
