### ISSUE TITLE
Update scheduler SPI to 1.0.2.RELEASE

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-scheduler-kubernetes#13]

**Comment by cppwfs** [comment]
This issue was create in response to the use of 1.1.0.BUILD-SNAPSHOT of scheduler in the SCDF-Server-K8's project.   After investigation,  SCDF-server-k8's should have used the 1.0.x. release.   The 1.1.was used to follow the version cadence of dataflow and later deemed not necessary.
