### ISSUE TITLE
Update to latest Boot, Cloud, and Deployer stack

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-scheduler-kubernetes#26]
As a user, when using the kubernetes-scheduler and overriding the supported properties, I run into the runtime CNF errors. Since SCDF 2.x line is on Boot 2.x, it is _required_ for the dependent libraries to not rely on older Boot (1.x) classes.

Depends on: https://github.com/spring-cloud/spring-cloud-scheduler/issues/30

**Comment by chrisjs** [comment]
also this will bump the project to 2.0.0
