### ISSUE TITLE
batch tasks that started by scheduler miss `External Execution Id` and `Logs` in Task Execution Details

### ISSUE THREAD

**Issue by WeekiXu** [spring-cloud/spring-cloud-scheduler-kubernetes#31]
Batch tasks that started by scheduler miss `External Execution Id` and `Logs` in Task Execution Details

this is composed task execution started by schedule and missed the `External Execution Id`
![](https://user-images.githubusercontent.com/21303064/71705217-82b23a80-2e19-11ea-9f23-f7d38b14972b.png)

this is a normal task execution started by composed task runner , it has External Execution Id and Logs
![](https://user-images.githubusercontent.com/21303064/71705269-b8efba00-2e19-11ea-8373-00625a2b7936.png)

**Comment by WeekiXu** [comment]
additional table task_execution.EXTERNAL_EXECUTION_ID has no value, and task_deployment has no record witch started by schedule.
![image](https://user-images.githubusercontent.com/21303064/71713182-98d4f080-2e43-11ea-873e-646e8d1b1daf.png)

these tasks is started by a composed-task-runner, and has no record with the composed-task-runner
![image](https://user-images.githubusercontent.com/21303064/71713235-d33e8d80-2e43-11ea-9ddc-a957c9116ea4.png)

**Comment by sabbyanandan** [comment]
Hi, @WeekiXu. Thank you for reporting this discrepancy. This may, however, be a problem in the handshake between the `spring-cloud-dataflow-scheduler-task-launcher` and SCDF API, so it will have to be reviewed at the level of SCDF first. 

Before we move it to the right repo, let's make sure you're on the latest version of SCDF. Please describe the versions in use, the task definition, and the defined schedules in your environment.

_ps: The `spring-cloud/spring-cloud-scheduler-kubernetes` is deprecated; the scheduler support is an integral component of `spring-cloud/spring-cloud-deployer-kubernetes` going forward._

**Comment by WeekiXu** [comment]
Thanks, current version: 
- spring-cloud-dataflow-server:2.2.1.RELEASE
- spring-cloud-skipper-server:2.1.2.RELEASE

I'll try the latest version soon.

**Comment by WeekiXu** [comment]
> Hi, @WeekiXu. Thank you for reporting this discrepancy. This may, however, be a problem in the handshake between the `spring-cloud-dataflow-scheduler-task-launcher` and SCDF API, so it will have to be reviewed at the level of SCDF first.
> 
> Before we move it to the right repo, let's make sure you're on the latest version of SCDF. Please describe the versions in use, the task definition, and the defined schedules in your environment.
> 
> _ps: The `spring-cloud/spring-cloud-scheduler-kubernetes` is deprecated; the scheduler support is an integral component of `spring-cloud/spring-cloud-deployer-kubernetes` going forward._

Done. Thanks. 

 scdf-server:2.3.0.RELEASE don't have this problem.
