### ISSUE TITLE
Add a CI plan to run the IT tests against the 1.8 through 1.10 clusters

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-scheduler-kubernetes#4]

**Comment by chrisjs** [comment]
i think this will depend on https://github.com/spring-cloud/spring-cloud-dataflow-acceptance-tests/pull/196 or similar being merged, right? @cppwfs

**Comment by cppwfs** [comment]
Not that I'm aware.   The PR above just introduces the ability to test Scheduling on DataFlow.  You can still run the original set of CI tests on dataflow.

**Comment by chrisjs** [comment]
plans added
